### ISSUE TITLE
Different height for multiple ace editors in one page

### ISSUE THREAD

**Issue by elgs** [angular-ui/ui-ace#103]
I use the recommended way to set the height of the editor by adding this global CSS:
```css
.ace_editor {
    height: 200px;
}
```

Now what if I have two ace editors, but I want to set different height for them. How can I set height separately for them?

Thanks,
Elgs
